### ISSUE TITLE
[Feature Request] Just wondering if it is possible to implement compatibility for 4GB Micro SD Cards and Up out of the box

### ISSUE THREAD

**Issue by 44cK3r** [metroid-maniac/SCFW#27] opened 2024-10-01 04:48 UTC
By possibly using the Super Card Software maybe or other software as the smallest Micro SD Card I have is 4GB as I'm having a really hard time trying to find a proper 2GB Micro SD Card that also isn't crazy expensive and I was able to find the software I don't know if it is the latest version though I'll have to check the WayBack Machine thank you

**Comment by OmDRetro** [comment] 2024-10-01 08:56
All the current SuperCard clones / reproductions should already be on the latest stock firmware v1.85

- Try holding `L` + `R` during the boot process then navigate the test menu once it appears by pressing `A` at least 4 times.
     - This should show you the prompt: `Now SC Version: X.XX`
     - Whatever number is shown here `X.XX` is the stock firmware version you have.

***

4 GB SD cards(micro SDs included) are NOT supported by the stock firmware. It was designed to only accept 2GB cards formatted in FAT16 ( FAT in windows ). Even if you can format a 4 GB card to FAT, the supercard will not accept it due to its firmware limitation. For this reason, flashing via Slot-1(Nintendo DS method) was added if in case you don't have a 2 GB card.

If you're looking for a tutorial to use the DS flashing method, you can check the video below:


[![Installing SCFW on the SuperCard SD 💾](https://img.youtube.com/vi/_YNGyMijD78/0.jpg)](https://www.youtube.com/watch?v=_YNGyMijD78&t=550s)

**Comment by 44cK3r** [comment] 2024-10-01 11:10
Ooo YAY thank you so very much

**Comment by OmDRetro** [comment] 2024-10-01 12:27
Closing this bug due to alternative flashing method already available

**Closed as completed by OmDRetro** 2024-10-01 12:27 UTC

**Comment by 44cK3r** [comment] 2024-10-02 00:51
It worked thank you so very much
