### ISSUE TITLE
Problem starting gba games

### ISSUE THREAD

**Issue by lorenzogamingtus** [metroid-maniac/SCFW#26] opened 2024-09-18 09:04 UTC
Hello, my GBA games don't work, they launch but make a shrill noise or freeze on (Nintendo Game Boy), except Mario and Luigi Superstar Saga, thank you

**Comment by OmDRetro** [comment] 2024-10-01 09:13
### Insufficient information

Please provide the ff.:

* Are you on a `Release` kernel or `Pre-release` kernel?
     * Are you using the kernel on a:
          * `SuperCard lite micro SD`
               * ![](https://wiki.gbatemp.net/w/images/3/35/SuperCard_lite.jpg)
          * `SuperCard Mini SD / Micro SD`
               * ![](https://gbatemp.net/attachments/538950259_910-jpg.269240/)
          * `SuperCard SD`
               * ![](https://wiki.gbatemp.net/w/images/f/f2/SuperCard_SD.jpg)
* Which game are you trying to load?

**Comment by TsilaAllaoui** [comment] 2024-10-01 12:14
Hi, me too. I use original AGB-001 with modded screen and only get white screen after loading game or infinite loop on loading kernel. I use Release version and SuperCard SD Phat one.
Tested on other AGB-001 but same. On GBA SP, Micro or NDS Lite it works smoothly thought

**Comment by lorenzogamingtus** [comment] 2024-10-01 12:24
hello thank you for answering me, I have a supercard micro sd in kernel release and I try Mario and Luigi superstar saga and the pokemon emerald and Metroid fusion moreover I have an error: flash id error: 00b9 0000c2ba Thank you

**Comment by TsilaAllaoui** [comment] 2024-10-01 12:35
@OmDRetro Is there some manipulation to do to make it work on AGB-001 model? I saw like booting in multiboot mode for 4 sec then loading  game but it doesn't work for me. Note that it works on SP, Micro and DS Lite

**Comment by OmDRetro** [comment] 2024-10-01 13:09
> hello thank you for answering me, I have a supercard micro sd in kernel release and I try Mario and Luigi superstar saga and the pokemon emerald and Metroid fusion moreover I have an error: flash id error: 00b9 0000c2ba Thank you

Duplicate of [Issue#10](https://github.com/metroid-maniac/SCFW/issues/10)
* Please patch the ROM with the `SuperCard 2.71 Patcher` OR you can follow the instructions below

***
### Metroid Fusion - USA & Australia ROM
* Has the increase ROM speed feature and must be disabled to boot on the SuperCard SD

You'll need the ff.:
* Hex Editor like HxD
* The ROM you're going to modify.
* Some knowledge in navigating/using your preferred hex editor.

Here's the modified hex pattern that disables the INCREASE ROM SPEED feature. Refer to the table below:

ROM | ORIGINAL HEX PATTERN | MODIFIED HEX PATTERN
:-:|:-:|:-:
Metroid Fusion (USA/Australia)| 00 00 04 02 00 04 | 00 00 00 00 00 00

Depending on the game you want to play:
* Look for the Original HEX pattern found in your ROM on your Hex Editor
* Replace ALL THE INSTANCES of the ORIGINAL HEX PATTERN with the MODIFIED HEX PATTERN
* Save the changes and transfer the modified ROM to your micro SD card.
* Do ensure that the file extension is in `*.GBA` format

**Comment by TsilaAllaoui** [comment] 2024-10-01 13:15
@OmDRetro Is this pattern valable for every game?

**Comment by OmDRetro** [comment] 2024-10-01 13:37
> @OmDRetro Is this pattern valable for every game?

Unlikely, but not impossible. If you're looking for an exhaustive list, you wouldn't find it here.

Sounds like you're allergic to the `SuperCard 2.71 patcher` 😅

I'd suggest to follow the instructions shown in [Issue#10](https://github.com/metroid-maniac/SCFW/issues/10)
* [Refer to this](https://github.com/metroid-maniac/SCFW/issues/10#issuecomment-2266148248)

**Comment by TsilaAllaoui** [comment] 2024-10-01 13:54
@OmDRetro Yeah, i'm not a big fan of the patcher 😅 any way to use the kernel to flash the rom? or another homebrew to do this? I can contribute if there is a lead you can show me. Also on the [Issue#10](https://github.com/metroid-maniac/SCFW/issues/10), the hex to edit was 04 12 80 E5 and here it's 04 02 00. How can i find what address is affected?

**Comment by OmDRetro** [comment] 2024-10-05 19:55
@lorenzogamingtus if you don't have any other concerns for this particular issue you have, I'll be closing this after 3 more days.
***
@TsilaAllaoui The hex pattern is the result of using the `SuperCard SD patcher 2.71` application. I think you made it clear that you don't want to use it, but I haven't experimented with other similar patchers out there to provide you with more assistance. As a team, we're already aware of the kernel's limitation as of late but implementing the patches to disable `Increase ROM speed` may take some time. On a personal note, I'd rather call it `Regulate ROM speed` by the time its implemented, but I'm not in charge of implementing that part of the patching system as of this time.

> [!IMPORTANT]
> **Do not expect OR ask for an ETA of when this feature will be done. It will be uploaded as soon as it's ready**

**Comment by lorenzogamingtus** [comment] 2024-10-05 20:09
Thanks you

**Comment by lorenzogamingtus** [comment] 2024-10-05 20:10
Thanks you

**Comment by lorenzogamingtus** [comment] 2024-10-05 20:10
Thanks you

**Closed as not planned** 2024-10-05 20:11 UTC
Labels: question
